### PR TITLE
Added support for authentication with Azure AD

### PR DESCRIPTION
**Pull request by ItalyPaleAle**
This PR adds support for authenticating with Cosmos DB using Azure AD: https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-setup-rbac

Docs have been updated to provide an example too.

### CODE REVIEW

**Review by a8m — APPROVED** [review]
Thanks for adding this @ItalyPaleAle

**Comment by ItalyPaleAle** [comment]
Thank you for the quick review @a8m! Are you also planning a release in the next days?

**Comment by ItalyPaleAle** [comment]
@a8m do you think you could publish a release in the next few days please? With Go modules, we kind of need a release to pull the latest code :)

**Comment by a8m** [comment]
Done. Thanks for the reminder and for your contribution 🙏 

> With Go modules, we kind of need a release to pull the latest code :)

For next time, you can use `go get github.com/a8m/documentdb@master` if you're blocked on this.

**Pull request merged**
